export const especialidadesOptions = [
  { value: 'Adolescentología', label: 'Adolescentología' },
  { value: 'Cardiología', label: 'Cardiología' },
  { value: 'Cirugía General', label: 'Cirugía General' },
  { value: 'Dermatología', label: 'Dermatología' },
  { value: 'Endocrinología', label: 'Endocrinología' },
  { value: 'Endodoncia', label: 'Endodoncia' },
  { value: 'Fisiatría', label: 'Fisiatría' },
  { value: 'Gastroenterología', label: 'Gastroenterología' },
  { value: 'Geriatría', label: 'Geriatría' },
  { value: 'Ginecología', label: 'Ginecología' },
  { value: 'Obstetricia', label: 'Obstetricia' },
  { value: 'Hepatología', label: 'Hepatología' },
  { value: 'Inmunología', label: 'Inmunología' },
  { value: 'Alergología', label: 'Alergología' },
  { value: 'Mastología', label: 'Mastología' },
  { value: 'Nefrología', label: 'Nefrología' },
  { value: 'Neumonología', label: 'Neumonología' },
  { value: 'Neurocirugía', label: 'Neurocirugía' },
  { value: 'Nutrición', label: 'Nutrición' },
  { value: 'Odontología', label: 'Odontología' },
  { value: 'Odontopediatría', label: 'Odontopediatría' },
  { value: 'Oftalmología', label: 'Oftalmología' },
  { value: 'Ortodoncia', label: 'Ortodoncia' },
  { value: 'Otorrinolaringología', label: 'Otorrinolaringología' },
  { value: 'Pediatría', label: 'Pediatría' },
  { value: 'Reumatología', label: 'Reumatología' },
  { value: 'Traumatología', label: 'Traumatología' },
  { value: 'Urología', label: 'Urología' },
];
