export * from './Navbar/navbar.component'
export * from './datatables/datatable.component';
export * from './footer/footer.component';
export * from './inputs/input.component';
export * from './quienes_somos/quienes_somos.component';
export * from './buttons/filledbutton.component';
export * from './buttons/unfilledbutton.component';
export * from './register-form/register-form.component';
export * from './login-form/login-form.component';
export * from './checkbox/checkbox.component';
export * from './vanguardia/vanguardia.component';
